### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Samuellekpor** [anyepeter/Portfolio-template#8]
A great project so far 🎉 and no issues with the accessibility of the webpage. 
I will kindly suggest you increase the font sizes because it can make the webpage more readable 👀 . Thanks

**Comment by Samuellekpor** [comment]
Please note also that it will be better to use 2 spaces for indentation in the HTML file for better readability of the code.

**Comment by anyepeter** [comment]
Set all the font size as required
